name: Sync Videos to S3 and CDN Invalidation

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "v9.5.0/images/videos/**"

jobs:
  sync-samples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install tools
        run: |
          curl -L -o /usr/local/bin/git-restore-mtime https://raw.githubusercontent.com/MestreLion/git-tools/master/git-restore-mtime
          chmod +x /usr/local/bin/git-restore-mtime

      - name: Restore file modification times from Git
        run: |
          git restore-mtime --no-directories v9.5.0/images/videos
          find v9.5.0/images/videos -type f -exec stat -c '%y %n' {} \; | sort

      - name: Sync v9.5.0/images/videos to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
        run: |
          aws s3 sync v9.5.0/images/videos s3://static-site.teamlab.com/v9.5.0/images/videos --delete
